### PR TITLE
Memory leakage test

### PR DESCRIPTION
**Pull request by gr2m**
Currently throws 

```
MemoryLeakError: Heap grew on 6 subsequent garbage collections (180 of 180 iterations) by 3.87 MB.

  Iterations between GCs: 30

  Final GC details:
  [    136 kB] [+ 1524x] [-  21x] Array
  [    120 kB] [+ 2250x] [-   0x] Closure
  [   80.6 kB] [+ 1440x] [-   0x] DLList
  [   72.5 kB] [+ 1410x] [-   0x] Object
  ... (13 more)
```

### CODE REVIEW

**Comment by gr2m** [comment]
Another test with just Bottleneck also looks like there are is a leak

```
const memwatch = require('@airbnb/node-memwatch')
const Bottleneck = require('bottleneck')

// Take first snapshot
var hd = new memwatch.HeapDiff()

for (let i = 0; i < 1000; i++) {
  new Bottleneck({
    maxConcurrent: 1
  })
}

// Take the second snapshot and compute the diff
const diff = hd.end()

console.log(diff.change.details)
```

Which logs

```
 { what: 'Array',
    size_bytes: 712432,
    size: '695.73 kb',
    '+': 10272,
    '-': 357 },
  { what: 'Bottleneck',
    size_bytes: 192000,
    size: '187.5 kb',
    '+': 1000,
    '-': 0 },
  { what: 'Closure',
    size_bytes: 896000,
    size: '875 kb',
    '+': 17000,
    '-': 0 },
  { what: 'Code',
    size_bytes: 7256,
    size: '7.09 kb',
    '+': 24,
    '-': 47 },
  { what: 'DLList',
    size_bytes: 672000,
    size: '656.25 kb',
    '+': 12000,
    '-': 0 },
  { what: 'Events',
    size_bytes: 80000,
    size: '78.13 kb',
    '+': 2000,
    '-': 0 },
  { what: 'LocalDatastore',
    size_bytes: 128000,
    size: '125 kb',
    '+': 1000,
    '-': 0 },
  { what: 'Native',
    size_bytes: 232232,
    size: '226.79 kb',
    '+': 1057,
    '-': 56 },
  { what: 'Object',
    size_bytes: 504072,
    size: '492.26 kb',
    '+': 10002,
    '-': 0 },
  { what: 'Promise',
    size_bytes: 48000,
    size: '46.88 kb',
    '+': 1000,
    '-': 0 },
  { what: 'Queues',
    size_bytes: 72120,
    size: '70.43 kb',
    '+': 1000,
    '-': 0 },
  { what: 'States',
    size_bytes: 48000,
    size: '46.88 kb',
    '+': 1000,
    '-': 0 },
  { what: 'String',
    size_bytes: 41936,
    size: '40.95 kb',
    '+': 1072,
    '-': 20 },
  { what: 'Sync',
    size_bytes: 112000,
    size: '109.38 kb',
    '+': 2000,
    '-': 0 },
  { what: 'Timeout',
    size_bytes: 256000,
    size: '250 kb',
    '+': 2000,
    '-': 0 },
  { what: 'Timer',
    size_bytes: 32064,
    size: '31.31 kb',
    '+': 1002,
    '-': 0 },
  { what: 'TimersList',
    size_bytes: 64,
    size: '64 bytes',
    '+': 1,
    '-': 0 },
  { what: 'system / Context',
    size_bytes: 368000,
    size: '359.38 kb',
    '+': 6000,
    '-': 0 } ]
```

All kind of things that don’t seem to be cleaned up. Maybe most notably there seem to be 1000 instances of Bottleneck that remain after the garbage collection

@SGrondin ☝️

**Comment by SGrondin** [comment]
I just figured out why... I'll run a few tests later today and update you on Slack

**Comment by gr2m** [comment]
Maybe add a test like this to Bottleneck itself? I think I’ll do the same to with my libs :)

**Comment by SGrondin** [comment]
Definitely. It's even more crucial for Bottleneck than almost any other type of lib out there.

**Comment by gr2m** [comment]
with `sgrondin/bottleneck#cleanup-refs` it still complaints but got much better

```
MemoryLeakError: Heap grew on 6 subsequent garbage collections (180 of 180 iterations) by 467 kB.

  Iterations between GCs: 30

  Final GC details:
  [   14.4 kB] [+ 120x] [-   0x] Timeout
  [   8.64 kB] [+ 120x] [-   0x] system / Context
  [   6.72 kB] [+ 120x] [-   0x] Closure
  [   5.76 kB] [+ 120x] [-   0x] Promise
  ... (3 more)
```

**Pull request merged**
