### PR TITLE
feat: v6

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Drop support for NodeJS v14, v16
BREAKING CHANGE: Drop the deprecated `onAbuseHandler` events

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
Shall we also use the deprecated `onAbuseLimit` while at it?

**Comment by wolfy1339** [comment]
Yeah. Sounds good

**Comment by kfcampbell** [comment]
I asked this on another issue, but I'm curious why we're removing Node 14 before its end of life, which is September.

**Review by kfcampbell — APPROVED** [review]
Makes sense, thank you.

**Comment by gr2m** [comment]
could we merge https://github.com/octokit/plugin-throttling.js/pull/594 first, and then remove the `minimalSecondaryRateRetryAfter` option that is deprecated as part of that PR? It's also quite an important fix, would be good if folks who use v5 today would get it, without the need to upgrade

**Comment by wolfy1339** [comment]
> could we merge https://github.com/octokit/plugin-throttling.js/pull/594 first, and then remove the `minimalSecondaryRateRetryAfter` option that is deprecated as part of that PR?

Sure thing :+1:

**Comment by gr2m** [comment]
> could we merge #594 first

it's done!

**Review by gr2m — DISMISSED** [review]

**Review by gr2m — APPROVED** [review]

**Pull request merged**
